{"spans": [{"name": "train_model_traced", "context": {"span_id": "0x5923e58af7e546af", "trace_id": "0x69235d4e9df23f4cb541f55de788bf51"}, "parent_id": null, "start_time": 1740523612232631502, "end_time": 1740523615368703554, "status_code": "ERROR", "status_message": "ValueError: DataFrame.dtypes for data must be int, float, bool or category. When categorical type is supplied, the experimental DMatrix parameter`enable_categorical` must be set to `True`.  Invalid columns:International plan: object, Voice mail plan: object", "attributes": {"mlflow.traceRequestId": "\"997be47e4f7e45039483b2728d18daee\"", "mlflow.spanType": "\"UNKNOWN\"", "step": "\"model_training\"", "mlflow.spanFunctionName": "\"train_model_traced\"", "mlflow.spanInputs": "{\"X_train\": \"   Total day minutes  ...  Voice mail plan\\n0              120.5  ...               no\\n1              150.3  ...              yes\\n\\n[2 rows x 8 columns]\", \"y_train\": \"[0 1]\", \"model_version\": \"test_1.0\"}"}, "events": [{"name": "exception", "timestamp": 1740523615368646754, "attributes": {"exception.type": "ValueError", "exception.message": "DataFrame.dtypes for data must be int, float, bool or category. When categorical type is supplied, the experimental DMatrix parameter`enable_categorical` must be set to `True`.  Invalid columns:International plan: object, Voice mail plan: object", "exception.stacktrace": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.12/site-packages/opentelemetry/trace/__init__.py\", line 589, in use_span\n    yield span\n  File \"/usr/local/lib/python3.12/site-packages/mlflow/tracing/fluent.py\", line 269, in start_span\n    yield mlflow_span\n  File \"/usr/local/lib/python3.12/site-packages/mlflow/tracing/fluent.py\", line 145, in _wrapping_logic\n    result = yield  # sync/async function output to be sent here\n             ^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/mlflow/tracing/fluent.py\", line 175, in wrapper\n    return wrapping_coro.send(fn(*args, **kwargs))\n                              ^^^^^^^^^^^^^^^^^^^\n  File \"/app/main.py\", line 73, in train_model_traced\n    return train_xgb_model(X_train, y_train, model_version=model_version)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/app/model_training.py\", line 241, in train_model\n    signature = mlflow.models.infer_signature(X_train, model.predict(X_train))\n                                                       ^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/xgboost/sklearn.py\", line 1633, in predict\n    class_probs = super().predict(\n                  ^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/xgboost/sklearn.py\", line 1248, in predict\n    predts = self.get_booster().inplace_predict(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/xgboost/core.py\", line 2512, in inplace_predict\n    data, fns, _ = _transform_pandas_df(data, enable_categorical)\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/xgboost/data.py\", line 603, in _transform_pandas_df\n    pandas_check_dtypes(data, enable_categorical)\n  File \"/usr/local/lib/python3.12/site-packages/xgboost/data.py\", line 569, in pandas_check_dtypes\n    _invalid_dataframe_dtype(data)\n  File \"/usr/local/lib/python3.12/site-packages/xgboost/data.py\", line 356, in _invalid_dataframe_dtype\n    raise ValueError(msg)\nValueError: DataFrame.dtypes for data must be int, float, bool or category. When categorical type is supplied, the experimental DMatrix parameter`enable_categorical` must be set to `True`.  Invalid columns:International plan: object, Voice mail plan: object\n", "exception.escaped": "False"}}]}], "request": "{\"X_train\": \"   Total day minutes  ...  Voice mail plan\\n0              120.5  ...               no\\n1              150.3  ...              yes\\n\\n[2 rows x 8 columns]\", \"y_train\": \"[0 1]\", \"model_version\": \"test_1.0\"}", "response": null}